version: "3.8"

services:
  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_PORT=5430
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVER_ADDRESS=postgres
      - SERVER_PORT=8000
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@postgres:5432/mydb
      - MEOW=MEOW 
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - ENVIRONMENT=production
    depends_on:
      - postgres
      # - redis
    networks:
      - app_network

  # redis:
  #   image: redis:7.4
  #   ports:
  #     - "6379:6379"
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
