version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8000
      - SERVER_PORT=8000
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/promo
      - POSTGRES_JDBC_URL=jdbc:postgresql://postgres:5432/promo
      - POSTGRES_USERNAME=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=mydb
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - ENVIRONMENT=production
    depends_on:
      - postgres
      # - redis


  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7.4
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
  